### ISSUE TITLE
Missing copyright licenses for Banner images

### ISSUE THREAD

**Issue by openarun** [dekzi/dde-store#30]
Hi @dekzi,

What are the copyright licenses for images in resources/banners and resources/icons ?

Thanks!

**Comment by ghost** [comment]
Hey @openarun,

For the icons in resources/icons, those were ported directly from Deepin's default icon pack. The banners came from multiple sources, and to be honest, I'm not entirely sure which came from where, so I don't know the copyright info off the top of my head.

Thanks for the work in the PRs you've opened, although to be honest, it's been a while since I've even touched this project (as you might be able to tell), so I'm honestly not sure about the implications/reasoning behind each one.

My absence from this project can mostly be attributed to lost interest/lack of motivation, the fact that I don't use UbuntuDDE (or DDE as a whole), and the fact that I'm 16 years old, so most of my time is taken up by highschool.

Would you be interested in having this repo transferred over to the UbuntuDDE organization for you to take over as a maintainer?

The last thing I'd want to do is leave this project as abandonware after all the work I've already put into it, so, worst case scenario, if I can't find a maintainer, I may archive this repo just to keep the source available.

**Comment by ghost** [comment]
> Hey @openarun,
> 
> For the icons in resources/icons, those were ported directly from Deepin's default icon pack. The banners came from multiple sources, and to be honest, I'm not entirely sure which came from where, so I don't know the copyright info off the top of my head.
> 
> Thanks for the work in the PRs you've opened, although to be honest, it's been a while since I've even touched this project (as you might be able to tell), so I'm honestly not sure about the implications/reasoning behind each one.
> 
> My absence from this project can mostly be attributed to lost interest/lack of motivation, the fact that I don't use UbuntuDDE (or DDE as a whole), and the fact that I'm 16 years old, so most of my time is taken up by highschool.
> 
> Would you be interested in having this repo transferred over to the UbuntuDDE organization for you to take over as a maintainer?
> 
> The last thing I'd want to do is leave this project as abandonware after all the work I've already put into it, so, worst case scenario, if I can't find a maintainer, I may archive this repo just to keep the source available.

Hey @openarun, just want to make sure you see this considering that the longer I just let this repo sit here, the longer it'll remain unmaintained, which neither of us want.

**Comment by openarun** [comment]
Hi @dekzi , I hadn't responded to it because I was preparing for an upload to Debian. 
https://tracker.debian.org/pkg/dde-store .
It has passed and is uploaded to Debian unstable now.
I have forked the project to https://github.com/UbuntuDDE/dde-store and I think we can maintain the fork. :)
Hope that makes sense! :)
Also, I would like to express a sincere thanks for your contribution so far to the UbuntuDDE Remix community, and DDE-based ecosystem by developing the store. :+1:

**Comment by ghost** [comment]
> Hi @dekzi , I hadn't responded to it because I was preparing for an upload to Debian. https://tracker.debian.org/pkg/dde-store . It has passed and is uploaded to Debian unstable now. I have forked the project to https://github.com/UbuntuDDE/dde-store and I think we can maintain the fork. :) Hope that makes sense! :) Also, I would like to express a sincere thanks for your contribution so far to the UbuntuDDE Remix community, and DDE-based ecosystem by developing the store. +1

Hey @openarun! Sounds great. Although the fork would obviously mean you have access to the code, could we still go through with transferring ownership of this main repo? That way we could keep the issues and pull requests, plus the old URL would redirect to the right place.

**Comment by ghost** [comment]
> > Hi @dekzi , I hadn't responded to it because I was preparing for an upload to Debian. https://tracker.debian.org/pkg/dde-store . It has passed and is uploaded to Debian unstable now. I have forked the project to https://github.com/UbuntuDDE/dde-store and I think we can maintain the fork. :) Hope that makes sense! :) Also, I would like to express a sincere thanks for your contribution so far to the UbuntuDDE Remix community, and DDE-based ecosystem by developing the store. +1
> 
> Hey @openarun! Sounds great. Although the fork would obviously mean you have access to the code, could we still go through with transferring ownership of this main repo? That way we could keep the issues and pull requests, plus the old URL would redirect to the right place.

Also, to clarify - for this to happen, I would need temporary permissions to create repos in the @UbuntuDDE org, and the fork you created would need to be deleted for a moment to be replaced with the transferred repo.

**Comment by openarun** [comment]
OK, we can proceed ahead. I have removed the fork.
Please proceed for the transfer.

**Comment by ghost** [comment]
@openarun Transfer completed! I can be removed from the organization now.

**Comment by openarun** [comment]
Thanks! I have preserved write access to the repository. :) If/when you want to contribute in future :)

**Comment by ghost** [comment]
Thanks! Would you be okay with me removing my Ko-fi link from this repo then? Considering that I won't be maintaining this going forward, I think it would be fair to forward people to donate to the actual maintainers. I'm probably going to delete my Ko-fi sometime this week anyways because of that, so, last chance if anyone wants to donate for the work I've already done I guess haha.

**Comment by openarun** [comment]
Done :)
